// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHeal1uVkcxzQEvorhFG998t3c3CFbIgE',
    appId: '1:103115219712:web:50801466847350ae29c9e5',
    messagingSenderId: '103115219712',
    projectId: 'vortex-chat-app',
    authDomain: 'vortex-chat-app.firebaseapp.com',
    storageBucket: 'vortex-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXsq1quI7Ty77oFIIQxsauh_YBf2hdlwk',
    appId: '1:103115219712:android:a8b694e28b1b3ba429c9e5',
    messagingSenderId: '103115219712',
    projectId: 'vortex-chat-app',
    storageBucket: 'vortex-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm7VqYuabIXPfhxMMQFxt-n6BepCdmMjk',
    appId: '1:103115219712:ios:300738027d2dde1b29c9e5',
    messagingSenderId: '103115219712',
    projectId: 'vortex-chat-app',
    storageBucket: 'vortex-chat-app.appspot.com',
    androidClientId: '103115219712-jb8pehb5skivqtfsch59p1hr3f369p7d.apps.googleusercontent.com',
    iosClientId: '103115219712-skevmqof7shs96gmrkh2eckoh1hdi9ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.vortex',
  );
}
